version: '3'

vars:
  ROOT_DIR: '{{.TASKFILE_DIR}}'
  QUARTZ_DIR: '{{.ROOT_DIR}}/quartz'
  QUARTZ_CONFIG_SOURCE: '{{.ROOT_DIR}}/config/quartz/quartz.config.ts'
  QUARTZ_CUSTOM_STYLE_SOURCE: '{{.ROOT_DIR}}/config/quartz/custom.scss'
  INFRA_DIR: '{{.ROOT_DIR}}/infra'
  SITE_ASSET_PATH: '{{.ROOT_DIR}}/quartz/public'
  STACK: 'QuartzSiteStack'
  CDK_ARGS: ''
  DOCS_SITE_URL: ''

tasks:
  precommit:
    desc: Install pre-commit hook
    cmds:
      - pre-commit install

  precommit:run:
    desc: Run pre-commit on changed files
    cmds:
      - pre-commit run

  precommit:run:all:
    desc: Run pre-commit on all files
    cmds:
      - pre-commit run --all-files

  docs:autolink:
    desc: Auto-link glossary for specified markdown files (FILES="docs/...md ...")
    cmds:
      - |
        bash -lc 'if [ -z "{{.FILES}}" ]; then
          echo "Usage: task docs:autolink FILES=\"docs/path/a.md docs/path/b.md\""
          exit 1
        fi
        python3 .opencode/skills/obsidian-doc-new/scripts/auto_link_glossary.py {{.FILES}}'

  docs:autolink:check:
    desc: Check glossary links for specified markdown files (FILES="docs/...md ...")
    cmds:
      - |
        bash -lc 'if [ -z "{{.FILES}}" ]; then
          echo "Usage: task docs:autolink:check FILES=\"docs/path/a.md docs/path/b.md\""
          exit 1
        fi
        python3 .opencode/skills/obsidian-doc-new/scripts/auto_link_glossary.py --docs-root docs --check {{.FILES}}'

  docs:autolink:changed:
    desc: Auto-link glossary for changed docs markdown files
    cmds:
      - |
        python3 - <<'PY'
        import shlex
        import subprocess
        import sys

        changed = subprocess.check_output(["git", "-c", "core.quotepath=false", "diff", "--name-only", "HEAD"], text=True)
        untracked = subprocess.check_output(["git", "-c", "core.quotepath=false", "ls-files", "--others", "--exclude-standard"], text=True)
        files = []
        for src in (changed.splitlines(), untracked.splitlines()):
            for path in src:
                path = path.strip()
                if not path.startswith("docs/") or not path.endswith(".md"):
                    continue
                if path.endswith("/README.md") or path.endswith("/TEMPLATE.md"):
                    continue
                files.append(path)
        files = sorted(set(files))
        if not files:
            print("No changed docs markdown files. Skipping auto-link.")
            sys.exit(0)

        cmd = ["python3", ".opencode/skills/obsidian-doc-new/scripts/auto_link_glossary.py", *files]
        print("+", " ".join(shlex.quote(x) for x in cmd))
        subprocess.run(cmd, check=True)
        PY

  docs:check:
    desc: Validate all docs and update reports/doc_check.md
    cmds:
      - python3 .opencode/skills/obsidian-doc-check/scripts/validate_vault.py --docs-root docs --report reports/doc_check.md

  docs:check:changed:
    desc: Validate changed docs and update reports/doc_check.md
    cmds:
      - |
        python3 - <<'PY'
        import shlex
        import subprocess
        import sys

        changed = subprocess.check_output(["git", "-c", "core.quotepath=false", "diff", "--name-only", "HEAD"], text=True)
        untracked = subprocess.check_output(["git", "-c", "core.quotepath=false", "ls-files", "--others", "--exclude-standard"], text=True)
        files = []
        for src in (changed.splitlines(), untracked.splitlines()):
            for path in src:
                path = path.strip()
                if not path.startswith("docs/") or not path.endswith(".md"):
                    continue
                if path.endswith("/README.md") or path.endswith("/TEMPLATE.md"):
                    continue
                files.append(path)
        files = sorted(set(files))
        if not files:
            print("No changed docs markdown files. Skipping validation.")
            sys.exit(0)

        cmd = [
            "python3",
            ".opencode/skills/obsidian-doc-check/scripts/validate_vault.py",
            "--docs-root",
            "docs",
            "--report",
            "reports/doc_check.md",
            "--targets",
            *files,
        ]
        print("+", " ".join(shlex.quote(x) for x in cmd))
        subprocess.run(cmd, check=True)
        PY

  docs:trace:
    desc: Generate static RTM views for Quartz
    cmds:
      - python3 .opencode/skills/obsidian-trace/scripts/generate_rtm_views.py --docs-root docs

  docs:guard:
    desc: Run docs auto-link and validation for changed docs
    cmds:
      - task docs:autolink:changed
      - task docs:check:changed

  quartz:prepare:
    desc: Clone Quartz if missing (not tracked)
    cmds:
      - |
        bash -lc 'if [ ! -d "{{.QUARTZ_DIR}}" ]; then
          git clone https://github.com/jackyzha0/quartz.git "{{.QUARTZ_DIR}}"
        else
          echo "Quartz already exists at {{.QUARTZ_DIR}}"
        fi'

  quartz:install:
    desc: Install Quartz dependencies
    deps:
      - quartz:prepare
    dir: '{{.QUARTZ_DIR}}'
    cmds:
      - npm ci

  quartz:sync-config:
    desc: Sync tracked Quartz config and style
    deps:
      - quartz:prepare
    cmds:
      - cp "{{.QUARTZ_CONFIG_SOURCE}}" "{{.QUARTZ_DIR}}/quartz.config.ts"
      - cp "{{.QUARTZ_CUSTOM_STYLE_SOURCE}}" "{{.QUARTZ_DIR}}/quartz/styles/custom.scss"

  quartz:build:
    desc: Build Quartz public from docs
    deps:
      - quartz:install
      - quartz:sync-config
    dir: '{{.QUARTZ_DIR}}'
    cmds:
      - npx quartz build -d ../docs

  infra:install:
    desc: Install CDK dependencies
    dir: '{{.INFRA_DIR}}'
    cmds:
      - npm ci

  infra:build:
    desc: Build CDK TypeScript
    deps:
      - infra:install
    dir: '{{.INFRA_DIR}}'
    cmds:
      - npm run build

  infra:synth:
    desc: Synthesize CDK template for docs delivery
    deps:
      - quartz:build
      - infra:build
    dir: '{{.INFRA_DIR}}'
    cmds:
      - npm run synth -- --context siteAssetPath={{.SITE_ASSET_PATH}} {{.STACK}} {{.CDK_ARGS}}

  infra:deploy:
    desc: Deploy docs assets with CDK
    deps:
      - quartz:build
      - infra:build
    dir: '{{.INFRA_DIR}}'
    cmds:
      - npm run deploy -- --context siteAssetPath={{.SITE_ASSET_PATH}} {{.STACK}} {{.CDK_ARGS}}

  docs:verify:
    desc: Verify deployed docs top page (optional DOCS_SITE_URL)
    cmds:
      - |
        bash -lc 'if [ -z "{{.DOCS_SITE_URL}}" ]; then
          echo "DOCS_SITE_URL is empty. Skip HTTP verification."
          exit 0
        fi
        curl -fsSL "{{.DOCS_SITE_URL}}/" > /dev/null
        curl -fsSL "{{.DOCS_SITE_URL}}/docs/" > /dev/null
        echo "Verified: {{.DOCS_SITE_URL}}/"'

  docs:deploy:
    desc: Run docs guard + Quartz build + CDK deploy
    cmds:
      - task docs:guard
      - task infra:deploy
      - task docs:verify
